name: my-workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3
      - name: Write appsetting
        env:
          APPSETTING: ${{ secrets.APPSETTING }}
        run: |
          echo '${{ secrets.APPSETTING }}' > QUERY/QUERY.API/appsettings.json

      - name: Build with Docker Compose
        run: docker compose build
  
  deploy:
    runs-on: [ self-hosted ]
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Prepare Configuration
        env:
          APPSETTING: ${{ secrets.APPSETTING }}
        run: |
          echo '${{ secrets.APPSETTING }}' > QUERY/QUERY.API/appsettings.json

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: 22
          script: |
            cd /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP
            git pull origin main
            echo '${{ secrets.APPSETTING }}' > QUERY/QUERY.API/appsettings.json
            docker compose down
            docker compose build --no-cache
            docker compose up -d
            docker system prune -f
