name: my-workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: [ self-hosted ]
    steps:
      - uses: actions/checkout@v3

      - name: Write appsettings
        run: |
          mkdir -p QUERY/QUERY.API COMMAND/COMMAND.API
          cat <<EOF > QUERY/QUERY.API/appsettings.json
          ${{ secrets.APPSETTING }}
          EOF

          cat <<EOF > COMMAND/COMMAND.API/appsettings.json
          ${{ secrets.APPSETTING }}
          EOF

      - name: Pull latest code
        run: |
             sudo mkdir -p /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP
              if [ ! -d /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP/.git ]; then
             sudo git clone https://github.com/PhucNghi176/E_COMMERCE_TEDDYBEAR_SHOP.git /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP
              fi
              cd /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP
              git pull origin main



      - name: Docker Compose Build & Deploy
        run: |
          cd /home/teddybear/E_COMMERCE_TEDDYBEAR_SHOP
          docker compose down
          docker compose build --no-cache
          docker compose up -d
          docker system prune -f
